server:
  host: localhost
  port: 8080
  writeTimeout: 15s
  gracefulShutdown: 30s

db:
  host: localhost
  user: postgres
  password: postgres
  name: roulette
  port: 5432
  migrate:
    enable: false
    dir: "migrations"

tg:
  botToken: 
  adminBotToken: 
  clientID: 
  clientHash: 
  clientPhone: 

ton:
  isTestnet: true
  tonCenterApiKey: 
  tonCenterApiKeyTestnet: 
  adminWallet: 
  mnemonic: 
