server:
  host: localhost
  port: 8080
  writeTimeout: 15s
  gracefulShutdown: 30s

db:
  host: localhost
  user: postgres
  password: postgres
  name: roulette
  port: 5432
  migrate:
    enable: false
    dir: "migrations"

tg:
  botToken: 7874545996:AAG8rOoyCyKm1wbZh3dhk7NwumFVDXmb0OA
  adminBotToken: 7698010051:AAFg5P1zionZ3wtfI9Z4hGrpoC2t_E6yx5Y
  clientID: 24161366
  clientHash: 18710bd3a0d52228d12e613305581a91
  clientPhone: +79378063683

ton:
  isTestnet: true
  tonCenterApiKey: ac1e1d07b5e92f90d81f5da9c6bde3e45e878d773fb33296ef9ea29326515069
  tonCenterApiKeyTestnet: 5305b4fb4a196cb74e20c6f3d0c461132ed9816be6e777cec00d48ec5b77dd30
  adminWallet: 0QDWVYgjURJziE1OjfdrjqKqP5BopnFDsNquFaEzqBqz1ajx
  mnemonic: salt silk scan dream uncle million axis bachelor indicate first lens predict bottom bench achieve whale spray kitchen entry chase shuffle sand endorse slogan
